### ISSUE TITLE
How to remove spotify from bottom

### ISSUE THREAD

**Issue by thekamalkashyap** [einargudnig/einargudni.com-old-js-version#2]
This site is just awesome. I would love to you this template but i am facing one problem how to remove that spotify icon from bottom . Help me with it please. Thanks you in advance.

**Comment by einargudnig** [comment]
You can remove or comment out the `<NowPlaying />` component in `LayoutWrapper.js`. That removes it from the page.

There are also other files connected to this component that you can remove after remove the `<NowPlaying /> component
- spotify.js
- now-playing.js
- fetcher.js
- Equalizer.js -> This one is currently not working

**Comment by thekamalkashyap** [comment]
Thanks man i just scrolled every file. How come i forget to see layoutwrapper.js
